// template-inspector demonstrates how to inspect the exact prompt template
// preface generated by the C-API template renderer before running generation.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/vladimirvivien/litertlm-go/pkg/litertlm"
)

func main() {
	model := flag.String("model", "", "path to .litertlm model file")
	backend := flag.String("backend", "cpu", "inference backend (cpu | gpu)")
	libPath := flag.String("lib", os.Getenv("LITERTLM_LIB"), "directory holding the LiteRT-LM shared libraries")
	systemPrompt := flag.String("system", "You are a helpful assistant.", "system prompt")
	prompt := flag.String("prompt", "What is the capital of France?", "prompt text")
	flag.Parse()

	if *model == "" {
		fmt.Fprintln(os.Stderr, "--model is required")
		os.Exit(2)
	}

	litertlm.SetMinLogLevel(litertlm.LogQuiet)

	ctx := context.Background()
	client, err := litertlm.New(ctx,
		litertlm.WithLib(*libPath),
		litertlm.WithModel(*model),
		litertlm.WithBackend(*backend),
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "new client: %v\n", err)
		os.Exit(1)
	}
	defer client.Close()

	// Initialize the Chat session with a system prompt
	chat, err := client.NewChat(ctx, litertlm.WithSystemPrompt(*systemPrompt))
	if err != nil {
		fmt.Fprintf(os.Stderr, "new chat: %v\n", err)
		os.Exit(1)
	}
	defer chat.Close()

	// Add a user turn to the conversation history (but don't send/execute yet)
	// On a Chat, we simulate history by calling RenderPreface on the conversation.
	fmt.Printf("--- Dry-run: Preface Template before Turn 1 ---\n")
	preface1, err := chat.Conversation().RenderPreface()
	if err != nil {
		fmt.Fprintf(os.Stderr, "RenderPreface: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(preface1)

	// Now send the first prompt
	fmt.Printf("\n--- Executing Turn 1 ---\n")
	reply, err := chat.Send(ctx, *prompt)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Send: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Reply: %s\n", reply.Text())

	// Inspect the template state after the turn is added to KV cache
	fmt.Printf("\n--- Dry-run: Preface Template after Turn 1 ---\n")
	preface2, err := chat.Conversation().RenderPreface()
	if err != nil {
		fmt.Fprintf(os.Stderr, "RenderPreface: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(preface2)
}
